SELECT wait_type
      ,waiting_tasks_count
      ,max_wait_time_ms
      ,wait_time_ms - signal_wait_time_ms AS resource_wait_time_ms -- Waiter list (SUSPENDED).
      ,signal_wait_time_ms -- Runnable queue (RUNNABLE).
      ,wait_time_ms AS total_wait_time_ms
      ,COALESCE(wait_time_ms / NULLIF(waiting_tasks_count, 0), 0) AS average_wait_time_ms
      ,wait_time_ms * 100.0 / SUM(wait_time_ms) OVER() AS percentage
FROM   sys.dm_os_wait_stats
WHERE  wait_time_ms > 0
       AND wait_type NOT IN ('BROKER_DISPATCHER'
                            ,'BROKER_EVENTHANDLER'
                            ,'BROKER_RECEIVE_WAITFOR'
                            ,'BROKER_TASK_STOP'
                            ,'BROKER_TO_FLUSH'
                            ,'BROKER_TRANSMITTER'
                            ,'CHECKPOINT_QUEUE'
                            ,'CHKPT'
                            ,'CLR_AUTO_EVENT'
                            ,'CLR_MANUAL_EVENT'
                            ,'CLR_SEMAPHORE'
                            ,'DBMIRROR_DBM_EVENT'
                            ,'DBMIRROR_DBM_MUTEX'
                            ,'DBMIRROR_EVENTS_QUEUE'
                            ,'DBMIRROR_WORKER_QUEUE'
                            ,'DBMIRRORING_CMD'
                            ,'DIRTY_PAGE_POLL'
                            ,'DISPATCHER_QUEUE_SEMAPHORE'
                            ,'EXECSYNC'
                            ,'FSAGENT'
                            ,'FT_IFTS_SCHEDULER_IDLE_WAIT'
                            ,'FT_IFTSHC_MUTEX'
                            ,'HADR_CLUSAPI_CALL'
                            ,'HADR_FILESTREAM_IOMGR_IOCOMPLETION'
                            ,'HADR_LOGCAPTURE_WAIT'
                            ,'HADR_NOTIFICATION_DEQUEUE'
                            ,'HADR_TIMER_TASK'
                            ,'HADR_WORK_QUEUE'
                            ,'KSOURCE_WAKEUP'
                            ,'LAZYWRITER_SLEEP'
                            ,'LOGMGR_QUEUE'
                            ,'ONDEMAND_TASK_QUEUE'
                            ,'PWAIT_ALL_COMPONENTS_INITIALIZED'
                            ,'QDS_ASYNC_QUEUE'
                            ,'QDS_PERSIST_TASK_MAIN_LOOP_SLEEP'
                            ,'QDS_SHUTDOWN_QUEUE'
                            ,'QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP'
                            ,'REQUEST_FOR_DEADLOCK_SEARCH'
                            ,'RESOURCE_QUEUE'
                            ,'SERVER_IDLE_CHECK'
                            ,'SLEEP_BPOOL_FLUSH'
                            ,'SLEEP_BUFFERPOOL_HELPLW'
                            ,'SLEEP_DBSTARTUP'
                            ,'SLEEP_DCOMSTARTUP'
                            ,'SLEEP_MASTERDBREADY'
                            ,'SLEEP_MASTERMDREADY'
                            ,'SLEEP_MASTERUPGRADED'
                            ,'SLEEP_MSDBSTARTUP'
                            ,'SLEEP_SYSTEMTASK'
                            ,'SLEEP_TASK'
                            ,'SLEEP_TEMPDBSTARTUP'
                            ,'SLEEP_WORKSPACE_ALLOCATEPAGE'
                            ,'SNI_HTTP_ACCEPT'
                            ,'SP_SERVER_DIAGNOSTICS_SLEEP'
                            ,'SQLTRACE_BUFFER_FLUSH'
                            ,'SQLTRACE_INCREMENTAL_FLUSH_SLEEP'
                            ,'SQLTRACE_WAIT_ENTRIES'
                            ,'WAIT_FOR_RESULTS'
                            ,'WAITFOR'
                            ,'WAITFOR_TASKSHUTDOWN'
                            ,'WAIT_XTP_HOST_WAIT'
                            ,'WAIT_XTP_OFFLINE_CKPT_NEW_LOG'
                            ,'WAIT_XTP_CKPT_CLOSE'
                            ,'XE_DISPATCHER_JOIN'
                            ,'XE_DISPATCHER_WAIT'
                            ,'XE_TIMER_EVENT')
ORDER  BY percentage DESC;